FROM node:argon

# Install curl and docker
# RUN apt-get update && apt-get install curl

RUN curl -sSL https://get.docker.com/ | sh

#Create app directory
RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

#Install app dependencies
COPY package.json /usr/src/app

RUN npm install -g swagger

RUN npm install

#COPY . /usr/src/app

#EXPOSE 10010

#CMD ["swagger", "project", "start"]
